#!/bin/bash


if [ $# -eq 0  ]
then
	echo "$0 [File-1] [File-2] .... [File-n]"
fi


for i in $@
do
	if [ -f $i ] 
	then
		file_name=`echo $i | sed "s/[]..*//"
		convert $i $file_name.png
	else
		echo "ERROR: $i is not a file"
	fi
done

echo "[+] File conversion completed"
